name: Build and deploy ASP.Net Core app 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./MusicStore.sln --configuration Release
        
      - name: Test with dotnet
        run: dotnet test ./MusicStore.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./MusicStore.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

#      - name: Upload artifact for deployment job
#        uses: actions/upload-artifact@v2
#        with:
#          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
