name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name : list files
        shell : bash
        run  : |
          pwd
          echo "hello"
