name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name : bash command
        shell : bash
        run  : |
          pwd
          echo "hello"

      - name : bash command
        shell : pwsh
        run  : |
          write-host "PS -= Hello"
