name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name : bash command
        shell : bash
        run  : |
          pwd
          echo "hello"

      - name : ps command
        shell : pwsh
        run  : |
          write-host "PS -= Hello"


      - name: Nexus Repo Publish
        shell : bash
        run  : |
          curl -v -u admin:admin --upload-file d://log.txt http://172.23.32.1:8081/repository/maven-releases/org/test/1.0/testlog.log
          

      
        
