name: Test Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell : bash
    steps:
      - name : bash command
        #shell : bash
        run  : |
          pwd
          echo "hello"

      - name : ps command
        #shell : pwsh
        #run  : |
        #  write-host "PS -= Hello"


      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://172.23.32.1:8081
          username: admin
          password: admin
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=pom
          filename: d://log.txt

     # - name: Nexus Repo Publish
     #   shell : bash
     #   run  : |
     #     curl -v -u admin:admin --upload-file d://log.txt http://172.23.32.1:8081/repository/maven-releases/org/foo/3.0/foo-3.0.pom
          

      
        
